import { Lead, LeadPriority, LeadStatus } from "./leads-types"

export const pipelineOrder: LeadStatus[] = ["new", "qualified", "proposal", "negotiation", "won", "lost"]

export const statusConfig: Record<LeadStatus, { label: string; className: string }> = {
  new: { label: "New", className: "bg-sky-500/10 text-sky-500 border-sky-500/20" },
  qualified: { label: "Qualified", className: "bg-indigo-500/10 text-indigo-500 border-indigo-500/20" },
  proposal: { label: "Proposal", className: "bg-purple-500/10 text-purple-500 border-purple-500/20" },
  negotiation: { label: "Negotiation", className: "bg-amber-500/10 text-amber-500 border-amber-500/20" },
  won: { label: "Won", className: "bg-emerald-500/10 text-emerald-500 border-emerald-500/20" },
  lost: { label: "Lost", className: "bg-zinc-500/10 text-zinc-500 border-zinc-500/20" },
}

export const priorityConfig: Record<LeadPriority, { label: string; className: string }> = {
  hot: { label: "Hot", className: "bg-red-500/10 text-red-500 border-red-500/20" },
  warm: { label: "Warm", className: "bg-orange-500/10 text-orange-500 border-orange-500/20" },
  cold: { label: "Cold", className: "bg-blue-500/10 text-blue-500 border-blue-500/20" },
}

export const agents = ["James Donovan", "Sarah Mitchell", "Michael Chen", "Emily Rodriguez"]

export const propertyOptions = [
  "Manhattan Penthouse",
  "Beverly Hills Estate",
  "Miami Beach Condo",
  "Malibu Beach House",
  "San Francisco Loft",
  "Dubai Marina Villa",
]

export const availableTags = [
  "VIP",
  "Investor",
  "First-time Buyer",
  "Cash Buyer",
  "Relocating",
  "International",
  "Urgent",
]

export const initialLeads: Lead[] = [
  {
    id: 1,
    name: "Sarah Mitchell",
    email: "sarah.m@email.com",
    phone: "+1 (555) 123-4567",
    whatsappNumber: "+15551234567",
    interestedProperties: ["Manhattan Penthouse"],
    property: "Manhattan Penthouse",
    budget: "$5.2M",
    status: "negotiation",
    priority: "hot",
    source: "Referral",
    assignedTo: "James Donovan",
    lastContact: "2 hours ago",
    avatar: "SM",
    score: 88,
    tags: ["VIP", "Cash Buyer"],
    reminder: { date: "May 30, 2026", note: "Call to discuss HOA terms and finalize offer" },
    attachments: [
      { name: "Financial_Statement.pdf", size: "2.4 MB", type: "pdf" },
      { name: "ID_Verification.pdf", size: "1.1 MB", type: "pdf" },
    ],
    notes: ["Requested private evening showing", "Needs legal review for HOA terms"],
    timeline: [
      { id: "1-a", title: "WhatsApp follow-up sent", time: "2h ago" },
      { id: "1-b", title: "Offer document shared", time: "Yesterday" },
      { id: "1-c", title: "Lead qualified by agent", time: "2 days ago" },
    ],
  },
  {
    id: 2,
    name: "Michael Chen",
    email: "m.chen@email.com",
    phone: "+1 (555) 234-5678",
    whatsappNumber: "+15552345678",
    interestedProperties: ["Beverly Hills Estate", "Malibu Beach House"],
    property: "Beverly Hills Estate",
    budget: "$8.7M",
    status: "proposal",
    priority: "warm",
    source: "Website",
    assignedTo: "Sarah Mitchell",
    lastContact: "1 day ago",
    avatar: "MC",
    score: 72,
    tags: ["Investor", "International"],
    attachments: [{ name: "Proof_of_Funds.pdf", size: "3.2 MB", type: "pdf" }],
    notes: ["Comparing with two Malibu properties"],
    timeline: [
      { id: "2-a", title: "Pricing proposal submitted", time: "1d ago" },
      { id: "2-b", title: "Discovery call completed", time: "3 days ago" },
    ],
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    email: "emily.r@email.com",
    phone: "+1 (555) 345-6789",
    whatsappNumber: "+15553456789",
    interestedProperties: ["Miami Beach Condo"],
    property: "Miami Beach Condo",
    budget: "$3.1M",
    status: "qualified",
    priority: "hot",
    source: "Social Media",
    assignedTo: "Michael Chen",
    lastContact: "5 hours ago",
    avatar: "ER",
    score: 81,
    tags: ["First-time Buyer", "Urgent"],
    reminder: { date: "May 29, 2026", note: "Schedule property viewing" },
    attachments: [],
    notes: ["Interested in fast closing window"],
    timeline: [
      { id: "3-a", title: "Qualification form completed", time: "5h ago" },
      { id: "3-b", title: "Lead created from Instagram ad", time: "1 day ago" },
    ],
  },
  {
    id: 4,
    name: "David Park",
    email: "david.park@email.com",
    phone: "+1 (555) 456-7890",
    whatsappNumber: "+15554567890",
    interestedProperties: ["San Francisco Loft", "Manhattan Penthouse"],
    property: "San Francisco Loft",
    budget: "$2.8M",
    status: "new",
    priority: "cold",
    source: "Email",
    assignedTo: "Emily Rodriguez",
    lastContact: "3 days ago",
    avatar: "DP",
    score: 45,
    tags: ["Relocating"],
    attachments: [],
    notes: ["Relocating from Seoul in Q3", "Needs pet-friendly building"],
    timeline: [{ id: "4-a", title: "Email inquiry received", time: "3d ago" }],
  },
  {
    id: 5,
    name: "Amanda Foster",
    email: "amanda.f@email.com",
    phone: "+1 (555) 567-8901",
    whatsappNumber: "+15555678901",
    interestedProperties: ["Malibu Beach House"],
    property: "Malibu Beach House",
    budget: "$16M",
    status: "won",
    priority: "hot",
    source: "Referral",
    assignedTo: "James Donovan",
    lastContact: "1 week ago",
    avatar: "AF",
    score: 95,
    tags: ["VIP", "Cash Buyer", "Investor"],
    attachments: [
      { name: "Purchase_Agreement.pdf", size: "5.1 MB", type: "pdf" },
      { name: "Signed_Contract.pdf", size: "4.7 MB", type: "pdf" },
      { name: "Property_Inspection.pdf", size: "8.2 MB", type: "pdf" },
    ],
    notes: ["Deal closed successfully", "Prefers wire transfer"],
    timeline: [
      { id: "5-a", title: "Contract signed", time: "1wk ago" },
      { id: "5-b", title: "Final walkthrough done", time: "10d ago" },
      { id: "5-c", title: "Offer accepted", time: "2wk ago" },
    ],
  },
  {
    id: 6,
    name: "Robert Chang",
    email: "r.chang@email.com",
    phone: "+1 (555) 678-9012",
    whatsappNumber: "+15556789012",
    interestedProperties: ["Dubai Marina Villa"],
    property: "Dubai Marina Villa",
    budget: "$4.5M",
    status: "new",
    priority: "warm",
    source: "Cold Call",
    assignedTo: "Sarah Mitchell",
    lastContact: "Yesterday",
    avatar: "RC",
    score: 58,
    tags: ["International"],
    attachments: [],
    notes: ["Looking to buy before end of year"],
    timeline: [{ id: "6-a", title: "Cold call — expressed interest", time: "Yesterday" }],
  },
  {
    id: 7,
    name: "Lisa Thornton",
    email: "l.thornton@email.com",
    phone: "+1 (555) 789-0123",
    whatsappNumber: "+15557890123",
    interestedProperties: ["Beverly Hills Estate"],
    property: "Beverly Hills Estate",
    budget: "$9.1M",
    status: "qualified",
    priority: "warm",
    source: "Referral",
    assignedTo: "James Donovan",
    lastContact: "2 days ago",
    avatar: "LT",
    score: 67,
    tags: ["Investor"],
    duplicateOf: 2,
    attachments: [{ name: "Investor_Profile.pdf", size: "1.8 MB", type: "pdf" }],
    notes: ["Possible duplicate — similar budget and property interest as Michael Chen"],
    timeline: [
      { id: "7-a", title: "Referral from existing client", time: "2d ago" },
      { id: "7-b", title: "Initial call completed", time: "2d ago" },
    ],
  },
]
